[package]
name = "libsponge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
itertools = "0.14.0"
libc = "0.2.177"
nix = "0.30.1"
rand = "0.9.2"
thiserror = "2.0.17"


[lib]
name = "libsponge"
path = "src/lib.rs"  
